@baseUrl = http://localhost:4000
@authToken = {{loginADMIN.response.body.token}}
@appointmentId = eb0d4047-7ac7-40f1-bcb6-36a4c7f34814
@ID_DO_PACIENTE =864e301f-0c3c-4468-aab6-e677872a948d
@ID_DO_MEDICO = "ssssssssaaas"
# ==========================
# 🚀 USERS / AUTH /  DOCTOR, ATTENDANT
# ==========================

# @name CadastrarUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "fullName": "Ingred Atendente",
  "email": "Ingredatendente@gmail.com",
  "password": "aaaasa",
  "specialty": "DrCARDIOLOGIA",
  "role": "ATTENDANT"
}

###
# @name loginADMIN
POST {{baseUrl}}/login
Content-Type: application/json

{
   "email": "Ingreddoutora@gmail.com",
  "password": "aaaasa"
}

###
# @name CheckToken
GET {{baseUrl}}/check
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

GET {{baseUrl}}/usersAll
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# ==========================
# 🚀 PATIENTS
# ==========================

# @name ListarTodosPacientes (Admin)
GET {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{authToken}}

###



###
# @name CadastrarPaciente
POST {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sa",
  "reason": "Dor de cabeça",
  "level": 3,
  "status": 0
}

### Filtrar triagem
GET {{baseUrl}}/patients
Authorization: Bearer {{authToken}}
### Filtrar pacientes em triagem (level === 0)
GET {{baseUrl}}/patients?filter=triage
Authorization: Bearer {{authToken}}

### Filtrar pacientes para médico (level !== 0 e status !== 2)
GET {{baseUrl}}/patients?filter=doctor
Authorization: Bearer {{authToken}}

### Filtrar pacientes atendidos (status === 2)
GET {{baseUrl}}/patients?filter=attended
Authorization: Bearer {{authToken}}
###
PATCH {{baseUrl}}/patients/{{ID_DO_PACIENTE }}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "level": 3
}

###
PATCH {{baseUrl}}/patients/status/b1fe111e-f29b-403f-86dd-4a5458c147fc
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "status": 2
}

###

### Atualizar status do paciente
@id_do_medico = d8b08881-56c1-47d9-9e99-50cb99a1536a
@id_do_paciente_agendamento = 864e301f-0c3c-4468-aab6-e677872a948d
POST {{baseUrl}}/appointments/{{id_do_medico}}/{{id_do_paciente_agendamento}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "endTime":   null,
  "status":    "PENDING"
}
# ==========================
# 🚀 Consultas/APPOINTMENTS
# ==========================


### Criar Appointment
# @name CadastrarAppointment
POST {{baseUrl}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "patientId": "{{ID_DO_PACIENTE}}",
  "doctorId": "{{ID_DO_MEDICO}}",
  "startTime": "2025-09-10T14:00:00.000Z",
  "endTime": "2025-09-10T15:00:00.000Z",
  "status": "SCHEDULED"
}

###

### Listar todos Appointments
# @name ListarAppointments
GET {{baseUrl}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Buscar Appointment por ID
# @name BuscarAppointment
GET {{baseUrl}}/appointments/doctor/02dca66f-3dbd-485d-9e91-fb337c68c4c2
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Atualizar Appointment
# @name AtualizarAppointment
PUT {{baseUrl}}/appointments/{{appointmentId}}/finish
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Deletar Appointment
# @name DeletarAppointment
DELETE {{baseUrl}}/appointments/{{appointmentId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json
