@baseUrl = http://localhost:4000
@authToken = {{loginADMIN.response.body.token}}
@appointmentId = e61f708d-adfb-44a2-8321-16ae28c78315
@ID_DO_PACIENTE =864e301f-0c3c-4468-aab6-e677872a948d
@ID_DO_MEDICO = "ssssssssaaas"
# ==========================
# 🚀 USERS / AUTH /  DOCTOR, ATTENDANT
# ==========================

# @name CadastrarUser
POST {{baseUrl}}/user
Content-Type: application/json

{
  "fullName": "Ingred On",
  "email": "IngredOliveira@gmail.com",
  "password": "aaaasa",
  "role": "ATTENDANT"
}

###
# @name loginADMIN
POST {{baseUrl}}/login
Content-Type: application/json

{
   "email": "IngredOliveira@gmail.com",
  "password": "aaaasa"
}

###
# @name CheckToken
GET {{baseUrl}}/check
Content-Type: application/json
Authorization: Bearer {{authToken}}



###

GET {{baseUrl}}/usersAll
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# ==========================
# 🚀 PATIENTS
# ==========================

# @name ListarTodosPacientes (Admin)
GET {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{authToken}}

###



###
# @name CadastrarPaciente
POST {{baseUrl}}/patients
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Sa",
  "reason": "Dor de cabeça",
  "level": 3,
  "status": 0
}

### Filtrar triagem
GET {{baseUrl}}/patients
Authorization: Bearer {{authToken}}
### Filtrar pacientes em triagem (level === 0)
GET {{baseUrl}}/patients?filter=triage
Authorization: Bearer {{authToken}}

### Filtrar pacientes para médico (level !== 0 e status !== 2)
GET {{baseUrl}}/patients?filter=doctor
Authorization: Bearer {{authToken}}

### Filtrar pacientes atendidos (status === 2)
GET {{baseUrl}}/patients?filter=attended
Authorization: Bearer {{authToken}}
###
PATCH {{baseUrl}}/patients/{{ID_DO_PACIENTE }}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "level": 3
}



###

### Atualizar status do paciente
@id_do_medico = d8b08881-56c1-47d9-9e99-50cb99a1536a
@id_do_paciente_agendamento = 864e301f-0c3c-4468-aab6-e677872a948d
POST {{baseUrl}}/appointments/{{id_do_medico}}/{{id_do_paciente_agendamento}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   "startTime": "2025-09-21T10:00:00Z",
  "endTime":   "2025-09-21T11:00:00Z",
  "status":    "PENDING"
}
# ==========================
# 🚀 Consultas/APPOINTMENTS
# ==========================


### Criar Appointment
# @name CadastrarAppointment
POST {{baseUrl}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "patientId": "{{ID_DO_PACIENTE}}",
  "doctorId": "{{ID_DO_MEDICO}}",
  "startTime": "2025-09-10T14:00:00.000Z",
  "endTime": "2025-09-10T15:00:00.000Z",
  "status": "SCHEDULED"
}

###

### Listar todos Appointments
# @name ListarAppointments
GET {{baseUrl}}/appointments
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Buscar Appointment por ID
# @name BuscarAppointment
GET {{baseUrl}}/appointments/{{appointmentId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

###

### Atualizar Appointment
# @name AtualizarAppointment
PATCH {{baseUrl}}/appointments/{{appointmentId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "FINISHED",
  "endTime": "2025-09-10T15:30:00.000Z"
}

###

### Deletar Appointment
# @name DeletarAppointment
DELETE {{baseUrl}}/appointments/{{appointmentId}}
Authorization: Bearer {{authToken}}
Content-Type: application/json
